Refactor Jenkinsfile stages and update echo messages

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -6,55 +6,42 @@ pipeline {
     }
 
     stages {
-        stage('build stage') {
+
+        stage('Build') {
             steps {
                 sh 'mvn clean package'
             }
             post {
                 success {
-                    echo "build success"
+                    echo 'Build Success'
                 }
                 failure {
-                    echo "build failure"
+                    echo 'Build Failed'
                 }
             }
         }
-        stage('build test') {
-            steps {
-                sh 'mvn test'
-            }
-            post {
-                success {
-                    echo "test success"
-                }
-                failure {
-                    echo "test failure"
-                }
-            }
-        }
-        stage("Run the spring application") {
-            steps { 
-                sh '''
-                    echo "Stopping existing Spring Boot application if running..."
-                    if pgrep -f spring_app_sak-0.0.1-SNAPSHOT.jar > /dev/null; then
-                        sudo pkill -f spring_app_sak-0.0.1-SNAPSHOT.jar
-                        echo "Application stopped."
-                    else
-                        echo "No existing application running."
-                    fi
 
-                    echo "Starting the Spring Boot application..."
-                    sudo java -jar target/spring_app_sak-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &
+        stage('Run Application') {
+            steps {
+                sh '''
+                pkill -f spring_app_sak || true
+
+                nohup java -jar target/*.jar > app.log 2>&1 &
+
+                sleep 10
+
+                pgrep -f spring_app_sak
                 '''
             }
         }
     }
+
     post {
         success {
-            echo "pipeline success"
+            echo 'Pipeline Success'
         }
         failure {
-            echo "pipeline failure"
+            echo 'Pipeline Failed'
         }
     }
 }
